### PR TITLE
GIP Channel Updates (Realiasing and Renaming)

### PR DESCRIPTION
**Pull request by Shinsina**
Screen Shot 2021-09-22 at 9 38 22 AM

Let me know when this gets deployed so I can update the section alias appropriately.

### CODE REVIEW

**Comment by Shinsina** [comment]
[GIP Channel name updates](https://trello.com/c/gqfq4waV/96-gip-channel-name-updates)

**Comment by Shinsina** [comment]
[GIP Channel name updates](https://trello.com/c/gqfq4waV/96-gip-channel-name-updates)

**Review by solocommand — APPROVED** [review]

**Comment by solocommand** [comment]
@Shinsina Deploying now

**Comment by solocommand** [comment]
Queries ran to update aliases and insert redirects:

```
db.getCollection('Redirects').insert([
  {
    from: '/snow-ice-management',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/snowpro'
  },
  {
    from: '/snow-ice-management/sand-salt-spreading',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/snowpro/sand-salt-spreading'
  },
  {
    from: '/snow-ice-management/snow-plowing',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/snowpro/snow-plowing'
  },
  {
    from: '/snow-ice-management/snow-blowing',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/snowpro/snow-blowing'
  },
  {
    from: '/snow-ice-management/deicing',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/snowpro/deicing'
  }
])

db.getCollection('Section').update({ alias: 'snow-ice-management' }, { $set: { alias: 'snowpro' } })
db.getCollection('Section').update({ alias: 'snow-ice-management/sand-salt-spreading' }, { $set: { alias: 'snowpro/sand-salt-spreading' } })
db.getCollection('Section').update({ alias: 'snow-ice-management/snow-plowing' }, { $set: { alias: 'snowpro/snow-plowing' } })
db.getCollection('Section').update({ alias: 'snow-ice-management/snow-blowing' }, { $set: { alias: 'snowpro/snow-blowing' } })
db.getCollection('Section').update({ alias: 'snow-ice-management/deicing' }, { $set: { alias: 'snowpro/deicing' } })
```

```
db.getCollection('Redirects').insert([
  {
    from: '/lawn-care-renovation',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care'
  },
  {
    from: '/lawn-care-renovation/spraying-spreading',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/spraying-spreading'
  },
  {
    from: '/lawn-care-renovation/seeding',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/seeding'
  },
  {
    from: '/lawn-care-renovation/fertilizer',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/fertilizer'
  },
  {
    from: '/lawn-care-renovation/tilling',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/tilling'
  },
  {
    from: '/lawn-care-renovation/dethatching',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/dethatching'
  },
  {
    from: '/lawn-care-renovation/fungicide',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/fungicide'
  },
  {
    from: '/lawn-care-renovation/aeration',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/aeration'
  },
  {
    from: '/lawn-care-renovation/organic-natural-products',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/organic-natural-products'
  },
  {
    from: '/lawn-care-renovation/herbicide',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/herbicide'
  },
  {
    from: '/lawn-care-renovation/pesticide',
    siteId: ObjectId("53c95fdd1784f8066eb2c891"),
    to: '/lawn-care/pesticide'
  },
])

db.getCollection('Section').update({ alias: 'lawn-care-renovation' }, { $set: { alias: 'lawn-care' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/aeration' }, { $set: { alias: 'lawn-care/aeration' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/dethatching' }, { $set: { alias: 'lawn-care/dethatching' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/fertilizer' }, { $set: { alias: 'lawn-care/fertilizer' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/fungicide' }, { $set: { alias: 'lawn-care/fungicide' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/herbicide' }, { $set: { alias: 'lawn-care/herbicide' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/organic-natural-products' }, { $set: { alias: 'lawn-care/organic-natural-products' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/pesticide' }, { $set: { alias: 'lawn-care/pesticide' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/seeding' }, { $set: { alias: 'lawn-care/seeding' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/spraying-spreading' }, { $set: { alias: 'lawn-care/spraying-spreading' } })
db.getCollection('Section').update({ alias: 'lawn-care-renovation/tilling' }, { $set: { alias: 'lawn-care/tilling' } })
```

**Pull request merged**
